name: Test

on:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install autoconf
        brew install automake
        brew install libtool

    - name: test
      run: |
        xcodebuild -showsdks
        /usr/bin/xcrun --sdk xros --find --show-sdk-path
        /usr/bin/xcrun --sdk xros --find ar
        /usr/bin/xcrun --sdk xros --find strip
        /usr/bin/xcrun --sdk xrsimulator --find --show-sdk-path
        /usr/bin/xcrun --sdk xrsimulator --find ar
        /usr/bin/xcrun --sdk xrsimulator --find strip

    - name: Build
      run: |
        make build platform=xros version=2.1.0-alpha
    
    - name: Update Package.swift
      run: |
        rm -rf ./Package.swift
        cp -f ./dist/release/Package.swift ./Package.swift

    - name: Push Package.swift
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: |
          - Package.swift
        message: "chore: release version 2.1.0-alpha"
        push: "origin HEAD:${{ github.ref_name }}"
        
    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: 2.1.0-alpha
        tag_name: 2.1.0-alpha
        files: |
          ./dist/release/*.txt
          ./dist/release/*.zip
        prerelease: true
        fail_on_unmatched_files: true
